# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CFGameSDK_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # pod 'AFNetworking'
  # pod 'Masonry'
  # pod 'YYModel'
  # pod 'SDWebImage', '~> 5.21.1'

  # Pods for CFGameSDK_Demo

end
